#pragma once

#define USB_LED_INDICATOR_ENABLE

#define RGB_MATRIX_TIMEOUT 150000
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_ALPHAS_MODS
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
